# =================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://18.132.248.81:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    languages:
        # First language is the default language
        - en-US
        - nl-NL
    # cors: true
    pretty_print: true
    limit: 10
    # templates:
      # path: /path/to/Jinja2/templates
      # static: /path/to/static/folder # css/js/img
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
#    manager:
#        name: TinyDB
#        connection: /tmp/pygeoapi-process-manager.db
#        output_dir: /tmp/
    # ogc_schemas_location: /opt/schemas.opengis.net

logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            en: Metadata records for marine geospatial data
            fr: instance par défaut de pygeoapi
        description:
            en: API provided by pygeoapi
            fr: pygeoapi fournit une API aux données géospatiales
        keywords:
            en:
                - geospatial
                - data
                - api
                - marine
            fr:
                - géospatiale
                - données
                - api
                - marin
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: http://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Geonovum / IIC Technologies
        url: https://www.geonovum.nl/
    contact:
        name: Pritchard, Jonathan
        position: Senior Technical Manager
        address: PO Box 508
        city: Amersfoot
        stateorprovince: 
        postalcode: 3800 AM
        country: Netherlands
        phone: 033 460 41 00
        fax: 
        email: jonathan.pritchard@iictechnologies.com
        url: www.iictechnologies.com
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:
    obs:
        type: collection
        title: Observations
        description: My cool observations
        keywords:
            - observations
            - monitoring
        context:
            - datetime: https://schema.org/DateTime
            - vocab: https://example.com/vocab#
              stn_id: "vocab:stn_id"
              value: "vocab:value"
        links:
            - type: text/csv
              rel: canonical
              title: data
              href: https://github.com/mapserver/mapserver/blob/branch-7-0/msautotest/wxs/data/obs.csv
              hreflang: en-US
            - type: text/csv
              rel: alternate
              title: data
              href: https://raw.githubusercontent.com/mapserver/mapserver/branch-7-0/msautotest/wxs/data/obs.csv
              hreflang: en-US
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2000-10-30T18:24:39Z
                end: 2007-10-30T08:57:29Z
        providers:
            - type: feature
              name: CSV
              data: tests/data/obs.csv
              id_field: id
              geometry:
                  x_field: long
                  y_field: lat


    ENC:
        type: collection
        title:
            en: S57 Electronic Chart Coverage (NL)
            nl: S57 Electronic Chart Coverage (NL)
        description:
            en: S57 electronic chart coverage and metadata, all Netherlands
            nl: tbd
        keywords:
            en:
                - Chart
                - Navigation
                - Oceans
                - Transportation
            nl:
                - XXX1
                - YYY1
        links:
            - type: text/html
              rel: canonical
              title: information
              href: http://mindef.nl/
              hreflang: nl
        extents:
            spatial:
                bbox: [-1.5,49.5,9,56]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2021-01-11T11:11:11Z
                end: null  # or empty (either means open ended)
        providers:
            - type: record
              name: TinyDBCatalogue
              data: tests/data/nl/chart_metadata-nl.tinydb
              id_field: id
              time_field: editionDate
              title_field: title
    NOAAENC:
        type: collection
        title:
            en: Global S-57 Electronic Chart Coverage Metadata (basic catalogue)
            fr: Le Metadata de Electronic Chart Coverage
        description:
            en: electronic chart coverage prototype, NOAA Charts only
            fr: tbd
        keywords:
            en:
                - Chart
                - Navigation
                - Oceans
                - Transportation
            fr:
                - lacs
                - plans d'eau
        links:
            - type: text/html
              rel: canonical
              title: information
              href: http://noaa.gov/
              hreflang: en-US
        extents:
            spatial:
                bbox: [-110,-60,110,60]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2021-01-11T11:11:11Z
                end: null  # or empty (either means open ended)
        providers:
            - type: record
              name: TinyDBCatalogue
              data: tests/data/noaa/chart_metadata.tinydb
              id_field: id
              time_field: editionDate
              title_field: title

    S-111:
        type: collection
        title:
            en: S-111 Water Level metadata
            fr: Le Metadata de Level d'eau
        description:
            en: electronic chart coverage prototype, NOAA only
            fr: tbd
        keywords:
            en:
                - Chart
                - Navigation
                - Oceans
                - Transportation
            fr:
                - lacs
                - plans d'eau
        links:
            - type: text/html
              rel: canonical
              title: information
              href: http://noaa.gov/
              hreflang: en-US
        extents:
            spatial:
                bbox: [-110,-60,110,60]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2021-01-11T11:11:11Z
                end: null  # or empty (either means open ended)
        providers:
            - type: record
              name: TinyDBCatalogue
              data: tests/data/noaa_s111/s111_metadata.tinydb
              id_field: id
              time_field: editionDate
              title_field: title
